### ISSUE TITLE
Which category should magisk go in customization or root or something else

### ISSUE THREAD

**Issue by XXDRD** [Psyhackological/AAA#18]

**Comment by Psyhackological** [comment]
> Magisk is a suite of open-source software for customizing Android, supporting devices higher than Android 5.0.
Some highlight features:
MagiskSU: Provide root access for applications
Magisk Modules: Modify read-only partitions by installing modules
MagiskBoot: The most complete tool for unpacking and repacking Android boot images

How about `## Android customization`? Do you have any better ideas?

**Comment by XXDRD** [comment]
What about `## Customization`  ?

**Comment by Psyhackological** [comment]
Yeah, but customization of what? PC? Apps?

**Comment by XXDRD** [comment]
what is this list about?

**Comment by Psyhackological** [comment]
I meant to be specific. I think you cannot have Customization alone. You have customization of something. Of your car, PC, Android, even wardrobe. Do you have different opinion?

**Comment by XXDRD** [comment]
Ok then will go with `## Android custumization`

**Comment by Psyhackological** [comment]
You meant `## Android customization`?

**Comment by XXDRD** [comment]
yup
