### ISSUE TITLE
Missing Google Play Links - GrapheneOS PDF Viewer

### ISSUE THREAD

**Issue by rshxyz** [Psyhackological/AAA#2]
Missing Google Play Links - GrapheneOS PDF Viewer
https://play.google.com/store/apps/details?id=app.grapheneos.pdfviewer.play&gl=US

**Comment by Psyhackological** [comment]
I've recently merged [pull request #4](https://github.com/Psyhackological/AAA/pull/4) that resolved the issue. Closing.
