### ISSUE TITLE
Clickable images

### ISSUE THREAD

**Issue by XXDRD** [Psyhackological/AAA#23]
Boomers love to click on images.
At least the thanks section images could link to their respective webpages

**Comment by Psyhackological** [comment]
Sure.
But to be honest I hate HTML in that sense.
a > img, right?

**Comment by XXDRD** [comment]
I think It could be just by markdown 

[![click me](https://c.tenor.com/x8v1oNUOmg4AAAAd/rickroll-roll.gif)](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by Psyhackological** [comment]
If you can do a resized image's height to 64 with link to it I will gladly learn this.

**Comment by Psyhackological** [comment]
However you can write some example markdown or unfortunately HTML to your proposal.

**Comment by XXDRD** [comment]
Markdown is a piece of shit, there is no standardization in this shitty thing. Everyone has their own markdown scheme.

I am gonna learn emcas org. I am done with obsidian and their different form of Markdown, which works only in their own app.

**Comment by XXDRD** [comment]
<a href="https://www.youtube.com/watch?v=LLFhKaqnWwk"><img alt="Click me" height="64" src="https://i.ytimg.com/vi/LLFhKaqnWwk/maxresdefault.jpg"></a>

**Comment by XXDRD** [comment]
Sadly, HTML seems to be the only option. There are some options to make markdown resize the image, but those don't work on GitHub's version of Markdown!

**Comment by Psyhackological** [comment]
> Markdown is a piece of shit, there is no standardization in this shitty thing. Everyone has their own markdown scheme.

Yeah I know that, I love this feeling when I'm editing offline in my own editor, then I push something to GitHub and it is all messed up. 

> I am gonna learn emcas org. I am done with obsidian and their different form of Markdown, which works only in their own app.

How does it going to help?

**Comment by Psyhackological** [comment]
>  <a href="https://www.youtube.com/watch?v=LLFhKaqnWwk">
>  <img alt="Click me" height="64" src="https://i.ytimg.com/vi/LLFhKaqnWwk/maxresdefault.jpg">
>  </a>

Yeah sure, however maybe to be sure to delete blue overlay around an image maybe add `style="text-decoration:none;"`? I don't know if it is needed, but that is just my rule.

```html
<a style="text-decoration:none;" href="https://www.youtube.com/watch?v=LLFhKaqnWwk">
	<img alt="Click me" height="64" src="https://i.ytimg.com/vi/LLFhKaqnWwk/maxresdefault.jpg">
</a>
```

**Comment by Psyhackological** [comment]
> Sadly, HTML seems to be the only option. There are some options to make markdown resize the image, but those don't work on GitHub's version of Markdown!

Yeah I know that. The only option on GitHub is resize beforehand manually sadly.

**Comment by XXDRD** [comment]
> > Markdown is a piece of shit, there is no standardization in this shitty thing. Everyone has their own markdown scheme.
> 
> Yeah I know that, I love this feeling when I'm editing offline in my own editor, then I push something to GitHub and it is all messed up.
> 
> > I am gonna learn emcas org. I am done with obsidian and their different form of Markdown, which works only in their own app.
> 
> How does it going to help?

GitHub will have option for org mode as README just like GitLab

**Comment by XXDRD** [comment]
## No diff, I guess 

### Yours
<a style="text-decoration:none;" href="https://www.youtube.com/watch?v=LLFhKaqnWwk">
    <img alt="Click me" height="64" src="https://i.ytimg.com/vi/LLFhKaqnWwk/maxresdefault.jpg">
</a>

### Mine
 <a href="https://www.youtube.com/watch?v=LLFhKaqnWwk">
 <img alt="Click me" height="64" src="https://i.ytimg.com/vi/LLFhKaqnWwk/maxresdefault.jpg">
 </a>

**Comment by Psyhackological** [comment]
Well check out my GitHub profile and markdown [about me](https://github.com/Psyhackological), then hover over any image. I don't know how to rid off it.

**Comment by Psyhackological** [comment]
> GitHub will have option for org mode as README just like GitLab

Could you remind me what org mode was? How could I benefit from it?

**Comment by XXDRD** [comment]
Read about org mode [here](https://orgmode.org/). 
Benefit - Standardized 
Some examples - https://github.com/novoid/github-orgmode-tests

**Comment by XXDRD** [comment]
So, HTML is the way to go for now until org is fully supported on github.
