### ISSUE TITLE
Microg

### ISSUE THREAD

**Issue by XXDRD** [Psyhackological/AAA#24]
Should it be added to the list?
If so, which category?

**Comment by Psyhackological** [comment]
To be honest, I don't think so.
As far as I know without a root there is no need to do that. The only time is when you need some app to work with Google. But maybe I'm wrong.

**Comment by XXDRD** [comment]
You don't need to work with microg. For example calyxos ships calyxos without root of course.
Maybe it shouldn't be added as it is not just one app but a collection of apps
