### ISSUE TITLE
Shelter Category 

### ISSUE THREAD

**Issue by XXDRD** [Psyhackological/AAA#25]
Which category should [Shelter](https://github.com/PeterCxy/Shelter) go to ?

**Comment by Psyhackological** [comment]
Maybe Android Customization? However as far as I know this app **did not have dark theme** sadly.

**Comment by XXDRD** [comment]
Ok, what about insular then… It works the same but has a dark theme

**Comment by Psyhackological** [comment]
Yeah, sure if you can test it beforehand.
