### ISSUE TITLE
Should I add Wikipedia 

### ISSUE THREAD

**Issue by XXDRD** [Psyhackological/AAA#26]
Btw which category?

**Comment by Psyhackological** [comment]
To be honest - I don't know. I'm just a regular Wikipedia user when I'm searching in my [SearXNG](https://paulgo.io) for it. Does it have a dark theme though?

**Comment by XXDRD** [comment]
White theme 
reading theme 
dark theme
black theme

image dimming

**Comment by Psyhackological** [comment]
Hmm, sure? I'm thinking about just `## Wikipedia` section, because everyone knows what Wikipedia is.
