### ISSUE TITLE
Kiwi Browser but without Tracking

### ISSUE THREAD

**Issue by Psyhackological** [Psyhackological/AAA#30]
<img alt="KiwiBrowserLogo" height="128" src="https://avatars.githubusercontent.com/u/40272275?v=4)">

I've wanted to add [Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser). It is open source on [GitHub](https://github.com/kiwibrowser/src), however I don't know why and how but in [version 98 there was no trackers](https://reports.exodus-privacy.eu.org/en/reports/228986/), but in current version it [has 3 trackers](https://reports.exodus-privacy.eu.org/en/reports/257307/). Is there any fork?

**Comment by XXDRD** [comment]
> there has been some controversy trelated to this browser in past 
here is a cummit post https://www.reddit.com/r/androidapps/comments/nt0pgc/kiwi_browser_is_a_spyware/
https://github.com/Tobi823/ffupdater/issues/35#issuecomment-1149764124

Decide yourself if you want it to added !

All the extensions a zoomer need are there is mull and the sandboxing a boomber is there in bromite. So the combination of bromite and mull is best for day to day usage.

**Comment by Psyhackological** [comment]
I see. Better not to add, thanks.
