### ISSUE TITLE
Brave Browser?

### ISSUE THREAD

**Issue by RaianIE** [Psyhackological/AAA#31]
I thought brave browser is also open-source. Am i missing something?

**Comment by XXDRD** [comment]
Also there is no reason to add brave as it don't offer anything else which bromite does

**Comment by Psyhackological** [comment]
> No chromiun based browser could be added to fdroid because of the messy code base. Only custum repositories could have chromium based browsers. Firefox based are on fdroid because firefox is truely free software where people outside mozilla actually contritube, resulting in a better code base

I did not know that. Weird, because Chromium based browsers have most of the market share hence in my mind that would be the opposite of what you have typed.

**Comment by Psyhackological** [comment]
> Also there is no reason to add brave as it don't offer anything else which bromite does

They do differ right, they are not the same browsers. Maybe someone synchronizes their PC with mobile app. I've done it myself.

**Comment by Psyhackological** [comment]
> but it is an alternative for bromite, isn't it? There is no rule saying that alternatives can't be in the list. But i believe it's the contrary.

Yeah it is. I'm going to test is soon again.

**Comment by XXDRD** [comment]
> Also there is no reason to add brave as it don't offer anything else which bromite does

Brave browser sync feature was almost broken the last time I used Brave. On the other hand Firefox sync works flawlessly.

Though I take it back that Brave doesn't offer different features

**Comment by XXDRD** [comment]
Every thing is good with this browser, leaving the fact that it does not support android native autofill
