### ISSUE TITLE
CloudStream is it working?

### ISSUE THREAD

**Issue by Psyhackological** [Psyhackological/AAA#32]
### CloudStream
<img alt="CloudStream" height="64" src="https://github.com/LagradOst/CloudStream-3/blob/master/app/src/main/ic_launcher-playstore.png?raw=true">

- [ ] Google Play
- [x] [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.lagradost.cloudstream3/)
- [x] [GitHub](https://github.com/LagradOst/CloudStream-3)
- [ ] Official page

I get constant error `No links found`. Could someone help?

**Comment by Nick1296** [comment]
I downloaded the app, I will be back in a few days after some testing.

**Comment by XXDRD** [comment]
> ### CloudStream
> 
> <img alt="CloudStream" height="64" src="https://github.com/LagradOst/CloudStream-3/blob/master/app/src/main/ic_launcher-playstore.png?raw=true">
> 
>     * [ ]  Google Play
> 
>     * [x]  [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.lagradost.cloudstream3/)
> 
>     * [x]  [GitHub](https://github.com/LagradOst/CloudStream-3)
> 
>     * [ ]  Official page
> 
> 
> I get constant error `No links found`. Could someone help?

It has a lot of connection problems which are very rare to get completely fixed because of the  no of site it supports

**Comment by Nick1296** [comment]
I used the prerelease version, and most of the sources work, however there might be issues with some sources, which I are not related to the app though

**Comment by XXDRD** [comment]
Yup most of sources are working and the app looking amazing. 
Should be added to the list !

**Comment by Psyhackological** [comment]
Well I guess, however in which section? It is more like a `## Streaming` or even `## Netflix`. haha

**Comment by XXDRD** [comment]
`## Streaming` would be enough 🤣
