### ISSUE TITLE
Kotatsu

### ISSUE THREAD

**Issue by Psyhackological** [Psyhackological/AAA#33]
<img src="https://raw.githubusercontent.com/KotatsuApp/Kotatsu/devel/.idea/icon.svg" alt="KotatsuLogo" width="256">

Has anyone used [Kotatsu](https://kotatsuapp.github.io/)?

**Comment by Nick1296** [comment]
No, but if you have used it, and it works, you can add it! Just make sure to follow the rules for adding apps

**Comment by Nick1296** [comment]
Oh sorry I mistook the username!
I can test that I we need a tester

**Comment by Psyhackological** [comment]
Yeah however I am not interested in mangas and anime, so extra help would he appreciated. That is why Tachiyomi was not tested by me.

**Comment by XXDRD** [comment]
I will test it.
Wait for a day or two.

**Comment by XXDRD** [comment]
Amazing UI ⇾ Cleaner than Tachiyomi 
Quick Animations ⇾ Love the animations 
No Bugs found 
Has a lot of manga sources, but comparatively much less to Tachiyomi though all the source are functional from the start though it Tachiyomi I have to install the extension of that source to use that source  ⇾ So much easier to use for newbies or Boomers
That's all, though Tachiyomi has more features, but it is minimal being super functional

**Comment by Psyhackological** [comment]
So this is a very good app for example - for me when I would like to start my manga & anime adventure?
