### ISSUE TITLE
Koler is not free.

### ISSUE THREAD

**Issue by noodlebreak** [Psyhackological/AAA#5]
It is not free. On Google Play it is paid.
https://play.google.com/store/apps/details?id=com.chooloo.www.koler

Which begs the question, does it offer a different version of the app which extra features or unlocked features on Google Play? Because anyone who knows it's on F-Droid wouldn't pay on Google Play. So why is it paid on the Play Store?
Because that violates your rule `Free of charge`.

Thoughts?

**Comment by Psyhackological** [comment]
Hi, please remember that:
- All of these apps are __Open Sourced__ and need maintenance, maintenance = money
- Google Play is the only place where developers can earn money with their app
- F-Droid or GitHub is the best way to get these apps.

So, if you do not want to pay on Google Play just download apk from [GitHub releases](https://github.com/Chooloo/koler/releases) or from [F-Droid](https://f-droid.org/packages/com.chooloo.www.koler/). My mindset is that Google Play links are optional (not all of them but in majority).

I use Koler on my daily basis and I think this is a Google Play apk with paywall. Nothing is missing.

Let me know your thoughts so I can close the issue.

**Comment by lukasz-mitka** [comment]
So maybe a `$` marker next to paid Google Play links would be a good idea?

**Comment by Psyhackological** [comment]
Which option?
# Option 1:
## Dialer
### Koler
<img alt="Koler" height="64" src="https://github.com/Chooloo/koler/blob/master/koler/src/main/ic_launcher-web.png?raw=true">

- [x] [$ Google Play](https://play.google.com/store/apps/details?id=com.chooloo.www.koler)
- [x] [F-Droid](https://f-droid.org/app/com.chooloo.www.koler)
- [x] [GitHub](https://github.com/Chooloo/koler)
- [ ] Official page

Like this?
# Option 2:
## Dialer
### Koler
<img alt="Koler" height="64" src="https://github.com/Chooloo/koler/blob/master/koler/src/main/ic_launcher-web.png?raw=true">

- [x] [Google Play $](https://play.google.com/store/apps/details?id=com.chooloo.www.koler)
- [x] [F-Droid](https://f-droid.org/app/com.chooloo.www.koler)
- [x] [GitHub](https://github.com/Chooloo/koler)
- [ ] Official page

Or do you have something else in mind?

**Comment by lukasz-mitka** [comment]
Keep the $ sign outside of the link IMO.
* [x]  [Google Play](https://play.google.com/store/apps/details?id=com.chooloo.www.koler) ($)

💲 could also be used:
* [x]  [Google Play](https://play.google.com/store/apps/details?id=com.chooloo.www.koler) 💲

**Comment by Psyhackological** [comment]
Yeah, sure.
I was thinking about emoji either. 

But now it gets more confusing. For example: [GoodTime](https://play.google.com/store/apps/details?id=com.apps.adrcotfas.goodtime). It is free, yes, but it has locked features behind paywall so, any ideas?

**Comment by lukasz-mitka** [comment]
Tricky one :)
🧱 maybe?

**Comment by Psyhackological** [comment]
Yeah.
Well... with 2 emojies I think the legend would be required. Aaand we started because we wanted to make it "less confusing". Rabbit hole.

**Comment by Psyhackological** [comment]
Plus I mentioned in the rules:
> Free of charge
App must be fully featured out of the box without some kind of paywall.

And then the user sees below:
🧱 - Paywall
💲 - Costs money

**Comment by lukasz-mitka** [comment]
Guess you could change it to sth like:
`Free of charge available`
`Most features are not paywalled` - But that opens some dangerous gates.
