### ISSUE TITLE
Suggestion: Add these apps?

### ISSUE THREAD

**Issue by SleepDaemon** [Psyhackological/AAA#50]
Delta Icon Pack (Links: [Official Site](https://delta-icons.github.io/), [Github](https://github.com/Delta-Icons/android), [Google Play](https://play.google.com/store/apps/details?id=website.leifs.delta), [IzzyDroid](https://apt.izzysoft.de/fdroid/index/apk/website.leifs.delta))

Harmonoid Music Player/YTM Streaming (Links: [Github](https://github.com/harmonoid/harmonoid)) P.S the android version is having a rework at the time of writing this, but should be out maybe in 2-3 months.

FoxyDroid (Links: [Github](https://github.com/kitsunyan/foxy-droid), [F-Droid](https://f-droid.org/packages/nya.kitsunyan.foxydroid/))

Trail Sense (Links: [Official Site](https://kylecorry.com/Trail-Sense/), [Github](https://github.com/kylecorry31/Trail-Sense), [F-Droid](https://f-droid.org/en/packages/com.kylecorry.trail_sense/), [Google Play](https://play.google.com/store/apps/details?id=com.kylecorry.trail_sense))

Privacy Indicators (Links: [Official Site](https://nitishgadangi.github.io/Privacy-Indicator-App/), [Google Play](https://play.google.com/store/apps/details?id=com.vishalroy.privacyindicator), [Github](https://github.com/NitishGadangi/Privacy-Indicator-App), [F-Droid](https://f-droid.org/en/packages/com.nitish.privacyindicator/))

Radio Garden (Links: [Official Site](http://radio.garden/), [Google Play](https://play.google.com/store/apps/details?id=com.jonathanpuckey.radiogarden))

Compass by R. Apps (Links: [Google Play](https://play.google.com/store/apps/details?id=apps.r.compass), [Galaxy Store](https://galaxystore.samsung.com/detail/apps.r.compass))

Black Screen: video screen off (Links: [Official Site](https://japp.io/black-screen/), [Google Play](https://play.google.com/store/apps/details?id=io.japp.blackscreen))

FakeStandby (Links: [Github](https://github.com/JonasBernard/FakeStandby), [F-Droid](https://f-droid.org/packages/android.jonas.fakestandby/))

SystemUI Tuner (Links: [Official Site](https://zwander.dev/dialog-systemuituner), [Google Play](https://play.google.com/store/apps/details?id=com.zacharee1.systemuituner))

OLEDBuddy (Links: [Google Play](https://play.google.com/store/apps/details?id=me.mikecroall.oledbuddy))

CamWings: Anti-Camera (Links: [Official Site](https://schiffer.tech/camwings-mobile.html), [Google Play](https://play.google.com/store/apps/details?id=com.schiffertech.camwings))

WTMP {Who Touched My Phone} (Links: [Official Site](https://wtmp.app/), [Google Play](https://play.google.com/store/apps/details?id=com.wtmp.svdsoftware))

Animity (Links: [Github](https://github.com/kl3jvi/animity))

HDO Box (Links: [Official Site](https://hdo.app/))

Overdrop - Weather & Widgets (Links [Google Play](https://play.google.com/store/apps/details?id=widget.dd.com.overdrop.free)) Due note it has a pro version

Smart Launcher (Links: [Official Site](https://www.smartlauncher.net/), [Google Play](https://play.google.com/store/apps/details?id=ginlemon.flowerfree))

**Comment by XXDRD** [comment]
You can start a [discussion](https://github.com/Psyhackological/AAA/discussions/43) for these 
which to add  and which not

**Comment by XXDRD** [comment]
`Foxy droid` was last  updated two year ago 
  > There is already `Droid-ify` in the list which is supposed to a foxy-droid replacement

`Privacy-indicator` is already built-in newer android version. So as everyone will upgrade as time passes to android 11 and 12. There is no use of this app, also this app has not been updated for a long time.

`Radio Garden`, `Compass`, `Black screen`, `OLEDBuddy`, `Who Touched My Phone?`, `HDO Box`, `Overdrop Weather`, `smartlauncher`  are  not  free and open source software. Hence, they can not be added to the list.

Add GitHub link to `SystemUITweaker` ⇒ https://github.com/zacharee/Tweaker

Can't understand what `CamWings` does and where is the source code of this app

**Comment by SleepDaemon** [comment]
> `Foxy droid` was last updated two year ago
> 
> > There is already `Droid-ify` in the list which is supposed to a foxy-droid replacement
> 
> `Privacy-indicator` is already built-in newer android version. So as everyone will upgrade as time passes to android 11 and 12. There is no use of this app, also this app has not been updated for a long time.
> 
> `Radio Garden`, `Compass`, `Black screen`, `OLEDBuddy`, `Who Touched My Phone?`, `HDO Box`, `Overdrop Weather`, `smartlauncher` are not free and open source software. Hence, they can not be added to the list.
> 
> Add GitHub link to `SystemUITweaker` ⇒ https://github.com/zacharee/Tweaker
> 
> Can't understand what `CamWings` does and where is the source code of this app

Understood, here is the correct link for SytemUI Tuner https://github.com/zacharee/SystemUITunerRedesign

**Comment by XXDRD** [comment]
> > `Foxy droid` was last updated two year ago
> > > There is already `Droid-ify` in the list which is supposed to a foxy-droid replacement
> > 
> > 
> > `Privacy-indicator` is already built-in newer android version. So as everyone will upgrade as time passes to android 11 and 12. There is no use of this app, also this app has not been updated for a long time.
> > `Radio Garden`, `Compass`, `Black screen`, `OLEDBuddy`, `Who Touched My Phone?`, `HDO Box`, `Overdrop Weather`, `smartlauncher` are not free and open source software. Hence, they can not be added to the list.
> > Add GitHub link to `SystemUITweaker` ⇒ https://github.com/zacharee/Tweaker
> > Can't understand what `CamWings` does and where is the source code of this app
> 
> Understood, here is the correct link for SytemUI Tuner https://github.com/zacharee/SystemUITunerRedesign

Add the apps complying with guidelines in discussion section of the repository

**Comment by SleepDaemon** [comment]
> > > `Foxy droid` was last updated two year ago
> > > > There is already `Droid-ify` in the list which is supposed to a foxy-droid replacement
> > > 
> > > 
> > > `Privacy-indicator` is already built-in newer android version. So as everyone will upgrade as time passes to android 11 and 12. There is no use of this app, also this app has not been updated for a long time.
> > > `Radio Garden`, `Compass`, `Black screen`, `OLEDBuddy`, `Who Touched My Phone?`, `HDO Box`, `Overdrop Weather`, `smartlauncher` are not free and open source software. Hence, they can not be added to the list.
> > > Add GitHub link to `SystemUITweaker` ⇒ https://github.com/zacharee/Tweaker
> > > Can't understand what `CamWings` does and where is the source code of this app
> > 
> > 
> > Understood, here is the correct link for SytemUI Tuner https://github.com/zacharee/SystemUITunerRedesign
> 
> Add the apps complying with guidelines in discussion section of the repository

Done, also sorry for the apps that dont comply

**Comment by XXDRD** [comment]
> > > `Foxy droid` was last updated two year ago
> > > > There is already `Droid-ify` in the list which is supposed to a foxy-droid replacement
> > > 
> > > 
> > > `Privacy-indicator` is already built-in newer android version. So as everyone will upgrade as time passes to android 11 and 12. There is no use of this app, also this app has not been updated for a long time.
> > > `Radio Garden`, `Compass`, `Black screen`, `OLEDBuddy`, `Who Touched My Phone?`, `HDO Box`, `Overdrop Weather`, `smartlauncher` are not free and open source software. Hence, they can not be added to the list.
> > > Add GitHub link to `SystemUITweaker` ⇒ https://github.com/zacharee/Tweaker
> > > Can't understand what `CamWings` does and where is the source code of this app
> > 
> > 
> > Understood, here is the correct link for SytemUI Tuner https://github.com/zacharee/SystemUITunerRedesign
> 
> Add the apps complying with guidelines in discussion section of the repository

??
You want me to add then ?

**Comment by XXDRD** [comment]
You create a fork of the project and edit the `README` then open a pull request to merge with the main repository

**Comment by SleepDaemon** [comment]
> You create a fork of the project and edit the `README` then open a pull request to merge with the main repository

Would prefer you do it for now, cause I'm a bit busy and I have setup my Git again cause it decided to break

**Comment by XXDRD** [comment]
> > You create a fork of the project and edit the `README` then open a pull request to merge with the main repository
> 
> Would prefer you do it for now, cause I'm a bit busy and I have setup my Git again cause it decided to break

ok

**Comment by XXDRD** [comment]
As most of which apps which follows rules are already added, this could be closed

**Comment by Psyhackological** [comment]
@XXDRD can you list approved apps that you put on the list and not approved with a good reason here? I would be grateful and then I could close the issue.

**Comment by XXDRD** [comment]
> @XXDRD can you list approved apps that you put on the list and not approved with a good reason here? I would be grateful and then I could close the issue.

# Approved

`Delta Icon Pack` 

`Trail Sense`

# Not approved ⇒

`Harmonoid Music Player/YTM Streaming`
 >  the app doesn't exist 

`FoxyDroid` 
> last updated 2 years ago

`Privacy Indicators`

`Radio Garden` `Compass by R. Apps` `Black Screen: video screen off` `HDO Box` `WTMP {Who Touched My Phone}`  `OLEDBuddy` `CamWings: Anti-Camera` `Overdrop - Weather & Widgets` `Smart Launcher`

> neither free as in freedom nor open source 

#### Will add after updating the `PRIVACY.md` and proper testing

`Animity`

`FakeStandby`

`SystemUI Tuner`

**Comment by Psyhackological** [comment]
Thank you, that is a really nice review. Closing. Have a wonderful day. :grin:
