### ISSUE TITLE
Email client 

### ISSUE THREAD

**Issue by lukasz-mitka** [Psyhackological/AAA#6]
I don't see any email clients and would love to see one.

**Comment by XXDRD** [comment]
I have used k-9 Mail for a month, and it does its job. 
It might not look as good as FairMail, but it is a really reliable app.

I don't know much FairMail other than that it has amazing looking UI

**Comment by Psyhackological** [comment]
@XXDRD If you can test FairMail, please do, so I may add these apps.

**Comment by XXDRD** [comment]
k-9 mail will become main stream in future as it is going to be the android client of thunderbird [view here](https://blog.thunderbird.net/2022/06/revealed-thunderbird-on-android-plans-k9/)

**Comment by Psyhackological** [comment]
Another good reason to put it on the list. Maybe I am too strict with **tested by me** rule.

**Comment by Psyhackological** [comment]
So, do we all agree to add `## E-Mail` category and `### K-9 Mail`?

**Comment by XXDRD** [comment]
> @XXDRD If you can test FairMail too, please do, so I may add these apps.

ok

**Comment by XXDRD** [comment]
Tested the app for 20-30 apps with all the basic features. NO BUGS FOUND yet. Though some features are locked as pro feature. 
It completely makes sense for an app like this to have premium features.
It has much more features than k-9mail and looks much better than k-9.
As it has so many settings options in it's setting menu, it would be overwhelming to anyone.

Tested on pixel 3a 
Android 12 
grapheneos
