### ISSUE TITLE
Replace Bromite with Cromite

### ISSUE THREAD

**Issue by dgcampbe** [Psyhackological/AAA#70]
It appears that Bromite has been abandoned and is now dangerously out of date. The community created a fork called Cromite to continue the project.
https://github.com/uazo/cromite

**Comment by Psyhackological** [comment]
Oh, wow, I use Bromite and I haven't even noticed. I wouldn't say:
> dangerously out of date

yet,

but still a shame that's not updated anymore. For now, I can replace it with Cromite until some update maybe will happen. [Closing](https://github.com/Psyhackological/AAA/commit/4627c8dd73bb07095de6060cc65d0db00dbc2e72)
