### ISSUE TITLE
Update Newpipe x Sponsorblock 

### ISSUE THREAD

**Issue by spider1163** [Psyhackological/AAA#74]
The project is now
https://github.com/polymorphicshade/Tubular

**Comment by Psyhackological** [comment]
## Updated:
- [a660b11](https://github.com/Psyhackological/AAA/commit/a660b112f5e7d874cb9c2be0536628fa53ce679d) - Replace NewPipe x SponsorBlock x Return YouTube Dislike with Tubular (229)
