### ISSUE TITLE
Replace Simple mobile tool by Fossify 

### ISSUE THREAD

**Issue by spider1163** [Psyhackological/AAA#75]
Simple mobile tool has been bought 
https://github.com/SimpleMobileTools/General-Discussion/issues/241

https://www.reddit.com/r/SimpleMobileTools/comments/19d280n/that_sweet_zipoapps_treatment/

You can replace them with Fossify
https://github.com/FossifyOrg

**Comment by Psyhackological** [comment]
## Replaced and done:
- [34c9c65](https://github.com/Psyhackological/AAA/commit/34c9c65dbf85269cbe2d0911def2877817b5cbff) - Fix some broken links and delete Simple Mobile Tools
- [04fcae0](https://github.com/Psyhackological/AAA/commit/04fcae0beab7dccbb43c63f41756840ff022686e) - Replace Simple Mobile Apps with Fossify alternatives
- [1dd129b](https://github.com/Psyhackological/AAA/commit/1dd129b4eda2bd4a5fb9747f98d7466bceb0ba34) - Add Fossify Music Player < Music Player (229)

I will add more when [they are available on F-Droid](https://search.f-droid.org/?q=fossify).
