### ISSUE TITLE
[Music Player] BlackHole Has Been 404'd Everywhere

### ISSUE THREAD

**Issue by Fmoment1** [Psyhackological/AAA#80]
Self explanatory title. BlackHole has vanished from F-Droid, GitHub and their own website.

**Comment by Psyhackological** [comment]
Thanks for letting me know @Fmoment1 !
Sad to see, but I will remove it soon after resolving issue with #79

**Comment by Psyhackological** [comment]
Fixed :)

- Fix issue with BlackHole vanishing from everywhere (#80) - [cb4c9f9](https://github.com/Psyhackological/AAA/commit/cb4c9f91b700d85f35474df100a944d399f879b5)
