### ISSUE TITLE
Update Clima and remove LTE Cleaner

### ISSUE THREAD

**Issue by victor6278** [Psyhackological/AAA#81]
Clima has been moved to Codeberg:
https://codeberg.org/Lacerte/clima

LTE Cleaner's development has ceased:
https://github.com/TheRedSpy15/LTECleanerFOSS?tab=readme-ov-file#notice

Sorry if this isn't the proper way to contribute.

**Comment by Psyhackological** [comment]
## Hi!

Thanks.

That's the proper way, I'm not picky. You can also lend me a hand by creaing a pull request ;)
Done with https://github.com/Psyhackological/AAA/commit/2e10cb973d728c5c3fdc1f1065390710fb5a1241.
