### ISSUE TITLE
clock-heart link outdated

### ISSUE THREAD

**Issue by nett00n** [Psyhackological/AAA#82]
https://github.com/Psyhackological/AAA#clock-heart

Project migrated from [here](https://github.com/qw123wh/new-clock?tab=readme-ov-file) to [here](https://github.com/BlackyHawky/Clock)

**Comment by Psyhackological** [comment]
## Hi!

Thanks, done: https://github.com/Psyhackological/AAA/commit/d57c0885d8524ea6aecdedddf7eebc789bde3888
